databases:
  - name: cybrscan-db
    databaseName: cybrscan
    user: cybrscan
    plan: free # Change to paid plan for production

services:
  - type: web
    name: cybrscan
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn simple_app:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cybrscan-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: APP_URL
        value: https://cybrscan.onrender.com # Update with your actual URL
      # Add these environment variables in Render dashboard:
      # - MAIL_SERVER
      # - MAIL_PORT
      # - MAIL_USE_TLS
      # - MAIL_USERNAME
      # - MAIL_PASSWORD
      # - MAIL_DEFAULT_SENDER
      # - STRIPE_PUBLIC_KEY
      # - STRIPE_SECRET_KEY
      # - STRIPE_WEBHOOK_SECRET
      # - ADMIN_EMAIL
      # - SUPPORT_EMAIL